Figure out what methods should exist between app and worker
eddieantonio/predictive-text-studio pull request #122
Opened 2020-10-26 01:19 UTC by Xuechunqiu

Fixes #108

2020-10-26 01:22 UTC, Xuechunqiu commented
This is just a version to see if I'm on the right track 😅

2020-10-26 01:23 UTC, Xuechunqiu commented on src/worker/predictive-text-studio-worker-impl.ts
> +  }
I'm not very sure about what should be done within these methods.

2020-10-26 16:01 UTC, eddieantonio requested changes

2020-10-26 16:01 UTC, eddieantonio commented on src/common/predictive-text-studio-worker.ts
> +   * Return how many words were added
```suggestion
   * @return how many words were added
```

2020-10-26 16:01 UTC, eddieantonio commented on src/common/predictive-text-studio-worker.ts
> +  generateKMPFromStorage(): Promise<Blob | void>;
Why was this method added? Who will call it and when?

2020-10-26 16:01 UTC, eddieantonio commented on src/common/predictive-text-studio-worker.ts
> +  setProjectData(metadata: Readonly<RelevantKmpOptions>): void;
I like this signature! Though I think it's better to add `Partial` as well:

```suggestion
  setProjectData(metadata: Partial<Readonly<RelevantKmpOptions>>): void;
```

2020-10-26 16:01 UTC, eddieantonio commented on src/worker/predictive-text-studio-worker-impl.ts
> +  async generateKMPFromStorage(): Promise<Blob | void> {
I like this method, but I think it should be `private` and **not** part of the App/Worker interface. 
```suggestion
  private async generateKMPFromStorage(): Promise<Blob | void> {
```

2020-10-26 16:01 UTC, eddieantonio commented on src/worker/predictive-text-studio-worker-impl.ts
> +  }
They should *register a callback* — aka, store the callback as a variable/property. These callbacks are called later, e.g., in `generateKMPFromStorage()`

```suggestion
  private _emitPackageCompileStart: () => void = () => {};
  private _emitPackageCompileError: (err: Error) => void = () => {};
  private _emitPackageCompileSuccess: (kmp: Blob) => void = () => {};

  onPackageCompileStart(callback: () => void): void {
    this._emitPackageCompileStart = callback;
  }

  onPackageCompileError(callback: (err: Error) => void): void {
    this._emitPackageCompileError = callback;
  }

  onPackageCompileSuccess(callback: (kmp: Blob) => void): void {
    this._emitPackageCompileSuccess = callback;
  }
```

2020-10-26 16:01 UTC, eddieantonio commented on src/worker/predictive-text-studio-worker-impl.ts
> +    });
Call the registered callback instead:

```suggestion
    this._emitPackageCompileStart();
```

2020-10-26 16:01 UTC, eddieantonio commented on src/common/predictive-text-studio-worker.ts
> +  onPackageCompileSuccess(kmp: Blob, callback: (kmp: Blob) => void): void;
```suggestion
  onPackageCompileError(callback: (err: Error) => void): void;
  /**
   * Register a callback that is called when the KMP package has succesfully compiled
   * @param callback
   */
  onPackageCompileSuccess(callback: (kmp: Blob) => void): void;
```

2020-10-26 16:01 UTC, eddieantonio commented on src/worker/predictive-text-studio-worker-impl.ts
> +      });
```suggestion
      this._emitPackageCompileError(new Error("Cannot find any files in the IndexedDB"));
```

2020-10-26 16:01 UTC, eddieantonio commented on src/worker/predictive-text-studio-worker-impl.ts
> +      const kmpFile = await linkStorageToKmp(this.storage);
`linkStorageToKMP()` can raise an error which _should_ be caught and passed to the `this. _emitPackageCompileError` callback.

2020-10-26 16:01 UTC, eddieantonio commented on src/worker/predictive-text-studio-worker-impl.ts
> +      return blob;
```suggestion
      this._emitPackageCompileSuccess(blob);
```

2020-10-26 16:01 UTC, eddieantonio commented on src/worker/storage.ts
> +  projectData: Dexie.Table<StoredProjectData, number>;
Why did you create a new table instead of extending the existing table?

2020-10-30 15:41 UTC, Xuechunqiu commented on src/app/components/BCP47Tag.svelte
> +      worker.setProjectData({ languages: [{ name: "", id: bcp47Tag }] });
We may use the bcp47Tag to generate the language name, or in an opposite way (let the user to input language name and we generate the bcp47Tag).

2020-11-02 15:48 UTC, IanSeng approved these changes

2020-11-02 17:20 UTC, eddieantonio approved these changes

2020-11-02 17:21 UTC, merged